apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdpipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicdpipeline
  template:
    metadata:
      labels:
        app: cicdpipeline
    spec:
      containers:
        - name: cicdpipeline
          image: johnogram/cicdpipeline:latest
          ports:
            - containerPort: 3000
          env:
          - name: ENV_NAME
            value: development
          - name: DOMAIN_NAME
            value: dev.minns.local
---
apiVersion: v1
kind: Service
metadata:
  name: cicdpipeline
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  type: LoadBalancer
  selector:
    app: cicdpipeline
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
