apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdpipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicdpipeline
  template:
    metadata:
      labels:
        app: cicdpipeline
    spec:
      containers:
        - name: cicdpipeline
          image: johnogram/cicdpipeline:first
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicdpipeline
spec:
  type: LoadBalancer
  selector:
    app: cicdpipeline
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
