name: Yarn Package Audit

on:
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Audit
        run: yarn audit
