name: Path To Staging

on:
  workflow_run:
    workflows:
      - Pull Request Checks
    branches:
      - staging
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Run Linter
        run: echo "Hello World!"
