name: Path To Staging

on:
  workflow_run:
    workflows:
      - Pull Request Checks
    branches:
      - staging
    types:
      - completed

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Staging
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Docker with AWS Credentials
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 975411558615.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker Image
        run: docker build -t johnogram-cicd .

      - name: Tag Docker Image
        run: docker tag johnogram-cicd 975411558615.dkr.ecr.eu-west-2.amazonaws.com/johnogram-cicd:staging

      - name: Push Docker Image
        run: docker push 975411558615.dkr.ecr.eu-west-2.amazonaws.com/johnogram-cicd:staging

  deploy:

    needs: build-and-push

    runs-on: ubuntu-latest

    steps:

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Update deployment file
        run: sed -i 's|johnogram/cicdpipeline:latest|975411558615.dkr.ecr.eu-west-2.amazonaws.com/johnogram-cicd:staging|' $GITHUB_WORKSPACE/k8s.yml

      - name: Check deployment
        run: cat $GITHUB_WORKSPACE/k8s.yml
