name: Path To Staging

on:
  workflow_run:
    workflows:
      - Pull Request Checks
    branches:
      - staging
    types:
      - completed

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Staging
        uses: actions/checkout@staging

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Check Something
        run: ls -lh

      - name: Build Docker Image
        run: docker build -t johnogram-cicd .

      - name: Tag Docker Image
        run: docker tag johnogram-cicd:staging ${{ secrets.AWS_ECR_REPO_URL }}/johnogram-cicd:staging

      - name: Push Docker Image
        run: docker push ${{ secrets.AWS_ECR_REPO_URL }}/johnogram-cicd:staging

